[package]
name = "my_todo_list"
version = "0.1.0"
authors = ["Your Name <youremail@example.com>"]
edition = "2018"
description = "A simple command-line to-do list manager written in Rust."
license = "MIT"

[dependencies]

[build-dependencies]

[dev-dependencies]
